### ISSUE TITLE
Add chat

### ISSUE THREAD

**Issue by SpaceOgre** [SpaceOgre/smarttv-twitch#8]
The original creator tried to add chat years ago via iframe but said it lagged a lot because of flash. It might work much better now. 

I think the fork for Tizien have chat so we can look and see if we can adapt it for this version.

#### Todo:

- [ ] Add flyout to the left for chat. 
- [ ] Resize video when chat is visible
- [ ] Test embed chat via iframe.

**Comment by Fansh1ne** [comment]
I think with chat feature this app would be complete.

**Comment by SpaceOgre** [comment]
@Fansh1ne I have added a basic chat via embedding the chat in an iframe. This is the official way to do it according to Twitch. I'm not sure how good it will look on a TV or if it will work/lagg. Please test if you got the time.

It is in this branch: https://github.com/SpaceOgre/smarttv-twitch/tree/feature/chat

**Comment by Fansh1ne** [comment]
I have tried the one from the link above and app is not working at all.

https://pixhost.to/show/268/130848828_img_20191223_222445.jpg

**Comment by SpaceOgre** [comment]
That's weird, I have not changed anything in the browsing part of the app 🤔
Is this how it looks from the start?

**Comment by Fansh1ne** [comment]
Yes. First time I started the app it looked like this. Tried starting it a few more times, same thing. It is indeed weird.

**Comment by SpaceOgre** [comment]
I forgot to merge the username fixes from master to the chat branch. Did that now but could not get it to work but did not have time to test it with userid set.

If you are upp for it you can try the chat branch again.

Oh does the 3.9.2 version work for you? Just trying to locate what I messed up :/
This JavaScript thing on a TV with like zero debug is driving me a bit crazy...

**Comment by SpaceOgre** [comment]
I think I found the problem, I had written `enableChat = true` instead of `enableChat: true` in the `config.js` file. It is now fixed.

**Comment by Fansh1ne** [comment]
Syntax error :) 3.9.2 working fine (20-30sec delay is still present when comapred to pc-chrome-twitch website). I will test it today when I get some time.

**Comment by Fansh1ne** [comment]
I have just tried it. It works like regular no chat version of the app. So basically streams are loading but there is no chat. I looked for option somewhere (to enable/disable chat) and haven't seen one. Tried a few different streamers, same, no chat visible.

**Comment by SpaceOgre** [comment]
The chat should show in the choose quality panel on the right. To show it press enter or left arrow.

**Comment by Fansh1ne** [comment]
I checked there, only choose quality panel, no chat. Looks same just in regular 3.9.2 release.

**Comment by SpaceOgre** [comment]
Okay, as long as enableChat is set to true in config.js then it should show if it works.
I guess the browser/engine used by the TV might just not be able to handle the embedded stuff from Twich sadly.

The Tizien fork is using websockets and connecting to the irc channel directly. Will look at this and see if I can use the same implementation here.

**Comment by Fansh1ne** [comment]
Thanks for trying. If you need help, let me know.
